### ISSUE TITLE
Add support for DOXYGEN_EXCLUDE_PATTERNS

### ISSUE THREAD

**Issue by luator** [machines-in-motion/breathing-cat#13]
Add an option to set `DOXYGEN_EXCLUDE_PATTERNS` in the Doxyfile, so the user can exclude parts of the C++ code from the documentation (e.g. some third-party library).

This is supported by the current CMake implementation of the documentation build and thus needs to be added to bcat before we can use it to replace the CMake code.

**Comment by luator** [comment]
It would be a bit annoying if those patterns would have to be passed as command line arguments all the time.  Instead I would add support for a config file (e.g. a `breathing_cat.toml` that needs to be added to the repo).  This could then also be used for #10 (instead of the original idea to extend conf.py).

**Comment by luator** [comment]
Proposal for the config file format (using toml):
```toml
[doxygen]
exclude_patterns = ["pattern1", "pattern2", "..."]

[intersphinx.mapping]
# short variant for convenience (if inventory=None)
robot_fingers = "https://open-dynamic-robot-initiative.github.io/robot_fingers"
# long variant for full support
robot_interfaces = {target = "https://open-dynamic-robot-initiative.github.io/robot_interfaces", inventory = "my_inv.txt"}
```
This can then easily be extended in the future if needed.

I would search for the file in "./breathing_cat.toml" and "doc[s]/breathing_cat.toml" in the package dir and alternatively provide a `--config` argument to explicitly specify a file.

@MaximilienNaveau Any feedback is welcome.

_Edit:_ Use `[intersphinx.mapping]`, so we can add other intersphinx parameters if needed.
